python -u features/count_encoding_hashtags.py --debug
python -u features/count_encoding_present_media.py --debug
python -u features/count_encoding_present_domains.py --debug
python -u features/count_encoding_present_links.py --debug
python -u features/connected_2nd_engaged_to_engaging.py --debug
python -u features/connected_2nd_engaging_to_engaged.py --debug
python -u features/count_encoding_in_tweetid_units.py --debug
python -u features/count_encoding_tweet_type.py --debug
python -u features/count_encoding_crossing.py --debug